# Используем официальный образ PostgreSQL
FROM postgres:15

# Устанавливаем переменные окружения для PostgreSQL
ENV POSTGRES_DB=todolist
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=1234

# Открываем порт 5432
EXPOSE 5432